https://www.perplexity.ai/search/b99dd1ac-2d40-4f7d-ba29-2972671abf18

In [ ]:
import numpy as np

np.random.seed(22)
scores = np.random.randint(50, 101, size=(50,5))
scores

In [ ]:
import pandas as pd

df = pd.DataFrame(scores,columns=["國文","英文","數學","生物","物理"],index=[f"學生{x}" for x in range(1,51)])
#設定表格每一欄、每一列的名稱
type(df) #df是DataFrame的實體

In [ ]:
[x**2 for x in range(10) if x< 4]

In [ ]:
df.columns.name = "科目" #設定欄資料名稱。DataFrame實體當中，有columns實體，columns實體屬性name。
df.index.name = "姓名" #設定列資料名稱
df

In [9]:
sum_series = df["國文"] + df["英文"] + df["數學"] + df["生物"] + df["物理"]
average_series = sum_series / 5
average_series

姓名
學生1     74.4
學生2     77.6
學生3     76.0
學生4     80.2
學生5     77.8
學生6     77.2
學生7     64.8
學生8     85.4
學生9     73.6
學生10    79.4
學生11    83.2
學生12    74.8
學生13    67.0
學生14    76.6
學生15    66.8
學生16    75.0
學生17    66.4
學生18    75.6
學生19    72.2
學生20    75.0
學生21    77.4
學生22    72.8
學生23    66.4
學生24    57.0
學生25    73.6
學生26    87.8
學生27    71.8
學生28    77.6
學生29    71.2
學生30    67.4
學生31    75.4
學生32    76.8
學生33    73.2
學生34    64.8
學生35    79.4
學生36    76.0
學生37    65.2
學生38    79.0
學生39    83.6
學生40    78.2
學生41    73.4
學生42    77.6
學生43    78.6
學生44    83.6
學生45    80.0
學生46    80.4
學生47    77.6
學生48    74.6
學生49    69.2
學生50    69.0
dtype: float64

In [10]:
df["總分"] = sum_series
df["平均"] = average_series
df

科目    國文  英文   數學   生物  物理   總分    平均
姓名
學生1   54  94   50   86  88  372  74.4
學生2   93  70   58   81  86  388  77.6
學生3   79  68   64   95  74  380  76.0
學生4   79  89   84   91  58  401  80.2
學生5   90  55   97   77  70  389  77.8
學生6   84  79   68   67  88  386  77.2
學生7   69  69   52   77  57  324  64.8
學生8   77  89   73   96  92  427  85.4
學生9   73  91   61   80  63  368  73.6
學生10  61  89   97   99  51  397  79.4
學生11  97  73   69   98  79  416  83.2
學生12  79  51   79   71  94  374  74.8
學生13  59  70   67   53  86  335  67.0
學生14  61  79   82   68  93  383  76.6
學生15  53  56   65   78  82  334  66.8
學生16  89  75   66   71  74  375  75.0
學生17  64  67   58   74  69  332  66.4
學生18  92  92   83   55  56  378  75.6
學生19  95  55   56  100  55  361  72.2
學生20  72  50   87   99  67  375  75.0
學生21  68  75   91   82  71  387  77.4
學生22  57  72   83   62  90  364  72.8
學生23  70  65   71   71  55  332  66.4
學生24  54  54   69   50  58  285  57.0
學生25  92  66   83   71  56  368  73.6
學生26  84  88   87   88  92  439  87.8
學生27  56  76   62   86  79  359  71.8
學生28  70  61   90   83  84  388  77.6
學生29  64  85   88   50  69  356  71.2
學生30  59  53   97   56  72  337  67.4
學生31  78  90   89   51  69  377  75.4
學生32  77  89   67   99  52  384  76.8
學生33  94  74   78   60  60  366  73.2
學生34  50  58   51   77  88  324  64.8
學生35  93  75   50   85  94  397  79.4
學生36  92  66   81   89  52  380  76.0
學生37  60  56   75   72  63  326  65.2
學生38  74  88   77   87  69  395  79.0
學生39  85  68  100   92  73  418  83.6
學生40  91  66   88   58  88  391  78.2
學生41  90  65   72   62  78  367  73.4
學生42  81  93   56   87  71  388  77.6
學生43  79  63   94   84  73  393  78.6
學生44  92  89   97   79  61  418  83.6
學生45  53  84  100   95  68  400  80.0
學生46  59  90   98   60  95  402  80.4
學生47  97  71   58   89  73  388  77.6
學生48  89  68   67   77  72  373  74.6
學生49  80  59   98   59  50  346  69.2
學生50  66  70   52   87  70  345  69.0